version: '2'
services:
  gosh:
    build: .
    volumes:
      - .:/code
      - ../pl-data/Dialogues/json:/code/json
      - ../pl-data/Dialogues/markdown:/code/markdown
      - ../pl-data/Dialogues:/code/csv
      - ../pl-data/Dialogues/images:/code/static/gameassets
    ports:
      - "2227:2222"
    expose:
      - "2222"
    env_file: playlogic.env
networks:
   default:
      external:
         name: nginxproxy_default
