version: '2'
services:
  gosh:
    image: torus/violet:latest
    volumes:
      - .:/code
      - ../NekoGameDemo/Dev/Dialogues/json:/code/json
      - ../NekoGameDemo/Dev/Dialogues:/code/csv
    ports:
      - "2222:2222"
    expose:
      - "2222"
    entrypoint: make run
