version: '2'
services:
  gosh:
    build: .
    volumes:
      - .:/code
      - ../Ukiyo/Dev/Dialogues/json:/code/json
      - ../Ukiyo/Dev/Dialogues:/code/csv
    ports:
      - "2227:2222"
    expose:
      - "2222"
    entrypoint: make run
    environment:
      VIRTUAL_HOST: ukiyo-96814.seaknot.dev
      LETSENCRYPT_HOST: ukiyo-96814.seaknot.dev
      LETSENCRYPT_EMAIL: toru-letsencrypt-ukiyo@torus.jp
networks:
   default:
      external:
         name: seaknotweb_default
