version: '2'
services:
  gosh:
    build: .
    volumes:
      - .:/code
      - ../Ukiyo/Dev/Dialogues/json:/code/json
      - ../Ukiyo/Dev/Dialogues:/code/csv
      - ../Ukiyo/Dev/Dialogues/images:/code/static/gameassets
    ports:
      - "2227:2222"
    expose:
      - "2222"
    entrypoint: make run
    env_file: ukiyo.env
networks:
   default:
      external:
         name: nginxproxy_default
